export const exercises = [
  {
    id: 'bench_press',
    name: 'Bench Press',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['barbell', 'bench'],
    muscleFocus: { chest: 0.75, triceps: 0.15, shoulders: 0.10 },
  },
  {
    id: 'incline_db_press',
    name: 'Incline Dumbbell Press',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['dumbbell', 'bench'],
    muscleFocus: { chest: 0.65, shoulders: 0.25, triceps: 0.10 },
  },
  {
    id: 'chest_fly',
    name: 'Chest Fly',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['dumbbell', 'machine'],
    muscleFocus: { chest: 0.90, shoulders: 0.10 },
  },
  {
    id: 'push_up',
    name: 'Push-Up',
    type: 'compound',
    loadType: 'bodyweight',
    equipment: [],
    muscleFocus: { chest: 0.60, triceps: 0.25, shoulders: 0.15 },
  },

  {
    id: 'pull_up',
    name: 'Pull-Up',
    type: 'compound',
    loadType: 'bodyweight',
    equipment: ['pull-up bar'],
    muscleFocus: { back: 0.70, biceps: 0.20, shoulders: 0.10 },
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['machine'],
    muscleFocus: { back: 0.70, biceps: 0.20, shoulders: 0.10 },
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['barbell'],
    muscleFocus: { back: 0.65, biceps: 0.20, shoulders: 0.15 },
  },
  {
    id: 'seated_row',
    name: 'Seated Cable Row',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['machine'],
    muscleFocus: { back: 0.65, biceps: 0.20, shoulders: 0.15 },
  },

  {
    id: 'bicep_curl',
    name: 'Bicep Curl',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['dumbbell', 'barbell'],
    muscleFocus: { biceps: 0.90, forearms: 0.10 },
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['dumbbell'],
    muscleFocus: { biceps: 0.60, forearms: 0.40 },
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['machine', 'barbell'],
    muscleFocus: { biceps: 0.85, forearms: 0.15 },
  },

  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['machine'],
    muscleFocus: { triceps: 0.90, shoulders: 0.10 },
  },
  {
    id: 'tricep_dips',
    name: 'Dips',
    type: 'compound',
    loadType: 'bodyweight',
    equipment: ['dip bars'],
    muscleFocus: { triceps: 0.60, chest: 0.30, shoulders: 0.10 },
  },
  {
    id: 'skullcrusher',
    name: 'Skullcrusher',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['barbell'],
    muscleFocus: { triceps: 0.90, shoulders: 0.10 },
  },

  {
    id: 'squat',
    name: 'Squat',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['barbell'],
    muscleFocus: { quads: 0.60, glutes: 0.30, hamstrings: 0.10 },
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['machine'],
    muscleFocus: { quads: 0.65, glutes: 0.25, hamstrings: 0.10 },
  },
  {
    id: 'lunges',
    name: 'Lunges',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['dumbbell'],
    muscleFocus: { quads: 0.50, glutes: 0.40, hamstrings: 0.10 },
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['machine'],
    muscleFocus: { quads: 0.95, },
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['machine'],
    muscleFocus: { hamstrings: 0.95 },
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['machine', 'bodyweight'],
    muscleFocus: { calves: 1.0 },
  },

  {
    id: 'shoulder_press',
    name: 'Shoulder Press',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['dumbbell', 'barbell'],
    muscleFocus: { shoulders: 0.70, triceps: 0.20, chest: 0.10 },
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['dumbbell'],
    muscleFocus: { shoulders: 0.90, traps: 0.10 },
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['dumbbell', 'machine'],
    muscleFocus: { shoulders: 0.80, back: 0.20 },
  },
  {
    id: 'shrugs',
    name: 'Shrugs',
    type: 'isolation',
    loadType: 'weighted',
    equipment: ['dumbbell', 'barbell'],
    muscleFocus: { traps: 0.95, },
  },

  {
    id: 'deadlift',
    name: 'Deadlift',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['barbell'],
    muscleFocus: { back: 0.40, glutes: 0.30, hamstrings: 0.20, traps: 0.10 },
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    type: 'compound',
    loadType: 'weighted',
    equipment: ['barbell'],
    muscleFocus: { hamstrings: 0.50, glutes: 0.30, back: 0.20 },
  },

  {
    id: 'plank',
    name: 'Plank',
    type: 'isolation',
    loadType: 'bodyweight',
    equipment: [],
    muscleFocus: { core: 1.0 },
  },
  {
    id: 'crunch',
    name: 'Crunch',
    type: 'isolation',
    loadType: 'bodyweight',
    equipment: [],
    muscleFocus: { core: 0.90, hip_flexors: 0.10 },
  },
  {
    id: 'leg_raise',
    name: 'Leg Raise',
    type: 'isolation',
    loadType: 'bodyweight',
    equipment: [],
    muscleFocus: { core: 0.85, hip_flexors: 0.15 },
  },
];